### ISSUE TITLE
browser compatibility and multiple image trackes

### ISSUE THREAD

**Issue by kino-dome** [akbartus/Simple-AR#2]
Hi! Thanks for this amazing library! 

I was wondering if you've tried it on Apple WebKit and how the performance compares to Chrome?

Also when you mention it currently supports a single image, does it mean it can only track one image at a time? Or do you mean it can only detect one image at each frame? I was wondering if I could provide 20 images to it to detect as long as I want one image to be tracked?

Ideally I wanna see if I can integrate it in an Ionic Capacitor app.

Thanks a ton!

**Comment by akbartus** [comment]
@kino-dome thank you for your inquiry. It should work with webkit. As for the second question - it detects one image at a time. But you can easily increase the number of images to be tracked so that it can track 20 images, single at a time. Working on improving the library to make this possible. Also soon adding UNITY support.

**Comment by akbartus** [comment]
I will consider the issue closed.
